version: '3'

services:
  shop:
    container_name: shop
    image: dockware/dev:latest
    ports:
      - "8080:80"     # apache2
      - "4443:443"   # apache2 https
    #volumes:
    #  - "./src:/var/www/html"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=0

## ***********************************************************************
##  NETWORKS
## ***********************************************************************
networks:
  web:
    external: false
